[package]
name = "digital_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = "0xb987f44f1cc3173c96f13c5735e7dd1707d1a476016e0c554ad396d209683417"
initial_creator_addr = "0xb987f44f1cc3173c96f13c5735e7dd1707d1a476016e0c554ad396d209683417"
minter = "0x3c41ff6b5845e0094e19888cba63773591be9de59cafa9e582386f6af15dd490"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
TokenMinter = { git = "https://github.com/aptos-labs/token-minter.git", rev = "a1c0c5e", subdir = "token-minter" }

[dev-dependencies]
